---
# hostnames and ips
master_ip: "172.16.0.10"
node1_ip:  "172.16.0.11"
node2_ip:  "172.16.0.12"
node3_ip:  "172.16.0.13"

master_hostname: "k8s-master"
node1_hostname: "k8s-node1"
node2_hostname: "k8s-node2"
node3_hostname: "k8s-node3"


username_env: vagrant
username_uid: vagrant
username_gid: vagrant
home_env: '/home/{{ username_env }}'

kubernetes_repo: "kubernetes-xenial main"
short_kubernetes_version: 1.21
default_kubernetes_version: 1.21.2-00
default_kubernetes_cni_version: 0.8.7-00

# chrony
chrony_pool: 2.ru.pool.ntp.org

# ceph
dashboard_port: 8099

# nginx-proxy
nginx_ceph_dashboard_port: 30010
