- name: "update packages"
  apt: update_cache=yes

- name: install additional tools
  package: name={{ item }} state=present
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  tags: common_install

- name: install chrony
  package: name=chrony state=present
  tags: common_install

- name: configure chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    force: yes
    owner: root
    group: root
  notify:
    - restart chrony
