- name: Common. Update packages.
  apt: update_cache=yes

- name: install additional tools
  package: name={{ item }} state=present
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - python3-distutils
  - python3-dev
  - libpq-dev
  tags: common_install

- name: Common. Download pip3.
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp

- name: Common. Install distutils.
  apt:
    name: python3-distutils
    state: present

- name: Install pip3.
  command: python3 /tmp/get-pip.py

- name: Install psycopg2.
  pip:
    name: psycopg2
    executable: pip3

- name: Install docker compose.
  pip:
    name: docker-compose
    state: present
    executable: pip3

- name: install chrony
  package: name=chrony state=present
  tags: common_install

- name: configure chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    force: yes
    owner: root
    group: root
  notify:
    - restart chrony
