---
- name: add GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags: kubernetes_repo_add

- name: set up kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ {{ kubernetes_repo }}
    update_cache: true
  tags: kubernetes_repo_add

- name: install bash-completion for auto complete kubectl commands
  apt: name=bash-completion state=present

- name: install kubeadm
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
  - "kubelet={{ default_kubernetes_version }}"
  - "kubectl={{ default_kubernetes_version }}"
  - "kubeadm={{ default_kubernetes_version }}"
  - "kubernetes-cni={{ default_kubernetes_cni_version }}"
  tags: test_121

- name: install openshift
  pip:
    name: openshift
    state: present
    executable: pip3

- name: hold upgrade kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubeadm
    - kubelet
    - kubernetes-cni
