- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell:
    swapoff -a
    #  when: kubernetes_installed is changed

- name: Disable SWAP in fstab (2/2)
  replace:
    path: /etc/fstab
    backup: yes
    regexp: '^.*swap.*sw.*0.*0'
    replace: '# swapoff'
    #  when: kubernetes_installed is changed

- name: check br_netfilter
  shell: 
    cmd: lsmod | grep br_netfilter
  register: br_netfilter_grep
  failed_when: br_netfilter_grep.rc == 2

- name: check br_netfilter
  shell: 
    cmd: lsmod | grep overlay
  register: overlay_grep
  failed_when: overlay_grep.rc == 2

- name: enabled br_netfilter
  modprobe:
    name: br_netfilter
    state: present
  when: br_netfilter_grep.rc == 1

- name: enabled overlay
  modprobe:
    name: overlay
    state: present
  when: overlay_grep.rc == 1

  #- name: add br_netfilter to k8s.conf (1/2)
  #lineinfile:
  #  state: present
  #  path: /etc/modules-load.d/k8s.conf
  #  line: "{{ item }}"
  #with_items:
  #  - br_netfilter

  #- name: add br_netfilter to k8s.conf (2/2)
  #sysctl:
  #  name: "{{ item.name }}"
  #  value: "{{ item.value }}"
  #  sysctl_file: /etc/sysctl.d/k8s.conf
  #  reload: yes
  #with_items:
  #  - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
  #  - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
