- name: Download Calico manifest.
  get_url:
    url: "{{ kubernetes_calico_manifest_file }}"
    dest: /tmp/calico.yaml

- name: Change autodetection section in Calico manifest.
  lineinfile:
    path: /tmp/calico.yaml
    insertafter: '.*value: "autodetect"'
    line: "{{ item }}"
  with_items:
    - '              value: "interface=eth1"'
    - '            - name: IP_AUTODETECTION_METHOD'

- name: Deploy Calico CNI.
  command: kubectl apply -f /tmp/calico.yaml
  tags:
    - calico_install
    - upgrade_cluster_components

- name: Check if Kubernetes Dashboard UI service already exists.
  shell: |
    set -o pipefail
    kubectl get services --namespace kube-system | grep -q kubernetes-dashboard
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false
  register: kubernetes_dashboard_service
  when: kubernetes_enable_web_ui | bool
  tags: test_112

- name: debug dashboard
  debug:
    var: kubernetes_dashboard_service
  tags: test_112

- name: Enable the Kubernetes Web Dashboard UI (if configured).
  command: "kubectl apply -f {{ kubernetes_web_ui_manifest_file }}"
  when:
  - kubernetes_enable_web_ui | bool
  - kubernetes_dashboard_service.rc != 0

- name: download helm
  unarchive:
    src: https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz
    dest: "{{ home_env }}/"
    remote_src: yes
  tags: helm_install

- name: move helm binary to PATH
  copy:
    src: "{{ home_env }}/linux-amd64/helm"
    dest: /usr/local/bin/
    mode: 0755
    force: yes
  tags: helm_install

- name: delete helm src
  file:
    state: absent
    path: "{{ home_env }}/linux-amd64"
  tags: helm_install
