---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-fedora-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-sc
