- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}
    create: yes

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: kubeadm reset
  shell: yes | kubeadm reset
  
- name: kubertenes initialize
  command: "kubeadm init --apiserver-advertise-address=10.8.8.11 --apiserver-cert-extra-sans=10.8.8.11 --node-name node-1 --pod-network-cidr=10.8.8.0/24 --kubernetes-version stable-1.21"

- name: preparing starting cluster
  become: false
  command: "{{ item }}"
  with_items:
  - mkdir -p /home/vagrant/.kube
  - cp -i /etc/kubernetes/admin.conf {{ user_info.home }}/.kube/config
  - chown {{ user_info.uid }}:{{ ansible_user_gid }} {{ user_info.home }}/.kube/config

- name: modify .bashrc
  lineinfile:
    path: "{{ user_info.home }}/.bashrc"
    line: "export KUBECONFIG={{ user_info.home }}/.kube/config"

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0} }}" dest="./join-command"
