- name: creating directory for weave password
  path: /var/lib/weave
  state: directory

- name: generate password for weave
  set_fact:
    weave_pwd: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"

- name: creating file witch containing weave password
  lineinfile:
    path: /var/lib/weave/weave.passwd
    state: present
    create: yes
    line: "{{ weave_pwd }}"
    
- name: apply weavenet
  command: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&password-secret=weave-passwd&env.IPALLOC_RANGE=192.168.0.0/24"
