- name: Configure Calico networking.
  command: "{{ item }}"
  with_items:
    - kubectl apply -f {{ kubernetes_calico_manifest_file }}

- name: Check if Kubernetes Dashboard UI service already exists.
  shell: |
    set -o pipefail
    kubectl get services --namespace kube-system | grep -q kubernetes-dashboard
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false
  register: kubernetes_dashboard_service
  when: kubernetes_enable_web_ui | bool

- name: Enable the Kubernetes Web Dashboard UI (if configured).
  command: "kubectl create -f {{ kubernetes_web_ui_manifest_file }}"
  when:
  - kubernetes_enable_web_ui | bool
  - kubernetes_dashboard_service.rc != 0

- name: download helm
  unarchive:
    src: https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz
    dest: "{{ home_env }}/"
    remote_src: yes
  tags: helm_install

- name: move helm binary to PATH
  copy:
    src: "{{ home_env }}/linux-amd64/helm"
    dest: /usr/local/bin/
    mode: 0755
    force: yes
  tags: helm_install

- name: delete helm src
  file:
    state: absent
    path: "{{ home_env }}/linux-amd64"
  tags: helm_install
