---
- name: Working with compirison operators
  hosts: all
  gather_facts: false
  vars:
    x: 6
    y: 10
  tasks:
    - debug:
        msg:
          - "x == y: {{ x == y }}"
          - "x != y: {{ x != y }}"
          - "x < y: {{ x < y }}"
          - "x > y: {{ x > y }}"
          - "x <= y: {{ x <= y }}"
          - "x >= y: {{ x >= y }}"

