---
- hosts: 10.8.8.11
  become: yes
  tasks:
  - name: yum update cache
    yum:
      update_cache: yes
    when: 
    - ansible_facts['distribution'] == "CentOS"

  - name: apt update cache
    apt:
      update_cache: yes
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
