apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - image: nginx:1.12
        name: nginx
        env:
          - name: test_variable
            value: foo
          - name: username
            valueFrom:
              secretKeyRef:
                name: new-secret
                key: user
          - name: user_password
            valueFrom:
              secretKeyRef:
                name: new-secret
                key: password
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            port: 80
            path: /
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
            httpGet:
              port: 80
              path: /
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 10
        startupProbe:
            httpGet:
              port: 80
              path: /
            periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
          - name: nginx-proxy-config
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-proxy-config
          configMap:
            name: nginx-proxy-config
