apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;
    
      location / {
        proxy_pass        http://172.16.0.10:8080/ceph/;
      }
    }
