- name: "update packages"
  apt: update_cache=yes
- name: upgrade packages
  apt:
    upgrade: yes

- name: install additional tools
  package: name={{item}} state=present
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - jq
