- name: adding admin group
  group:
    name: "{{ item }}"
    state: present
  with_items:
  - admin
  - docker
  ignore_errors: true

- name: adding k8s user NOPASSWD in sudoers file
  lineinfile:
    path: /etc/sudoers
    regexp: '^%admin'
    state: present
    line: '%admin ALL=(ALL) NOPASSWD: ALL'

- name: get k8s info for checking exist it or not.
  getent:
    database: passwd
    key: k8s
  ignore_errors: true
  register: user_existing

- name: generate password value
  set_fact:
    pwd_alias: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"
  when: user_existing is failed

- name: write password in local file
  local_action: 
    module: lineinfile 
    path: ./k8s_passwd
    regexp: '^\A(.+)$'
    line: "{{ pwd_alias }}"
    state: present
    create: yes
  when: user_existing is failed

- name: creating kubernetes user
  user:
    name: k8s
    state: present
    password: "{{ pwd_alias | password_hash('sha512') }}"
    shell: /bin/bash
    create_home: yes
    groups: admin,docker 
  register: user_info
  when: user_existing is failed
