- name: Postgresql. Allow LAN access.
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    insertafter: '# IPv4 local connections:'
    line: "host all all 192.168.88.0/24 md5"

- name: Postgresql. Open postgresql port.
  replace:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: "#listen_addresses = 'localhost'"
    replace: "listen_addresses = 'localhost, {{ node1_ip }}'"

- name: Postgresql. create default user password.
  become: true
  become_method: sudo
  become_user: postgres
  postgresql_user:
    db: postgres
    name: postgres
    password: "{{ default_password }}"
    state: present

- name: allow CNI access to postgres for keycloak user.
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    insertafter: '# IPv4 local connections:'
    line: "host keycloak keycloak 10.244.0.0/16 md5"
  when: keycloak_enabled

- name: Postgresql. Create replication user.
  become: true
  become_method: sudo
  become_user: postgres
  postgresql_user:
    name: repuser
    password: "{{ default_password }}"
    role_attr_flags: REPLICATION
  when: postgres_replication_enabled
  tags: 
    - postgres_replication_config
    - postgres_create_replication_user

- name: allow CNI access to postgres for repuser
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    insertafter: '# IPv4 local connections:'
    line: "host replication repuser {{ postgres_standby_1_ip }}/32 md5"
  when: postgres_replication_enabled
  tags: postgres_replication_config

- name: Postgresql. Set up streaming replication on primary server.
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    insertafter: '#wal_level = .*'
    line: | 
          wal_level = replica
          max_wal_senders = 5
          wal_keep_segments = 32
          archive_mode = on
          archive_command = 'cp %p /srv/archive/postgresql/data/%f'
  when: postgres_replication_enabled
  tags: postgres_replication_config

- name: Postgresql. Create directory for archive.
  file:
    path: "{{ postgres_archive_path }}"
    state: directory
    mode: '0700'
    owner: postgres
    group: postgres

- name: restart postgres now
  service:
    name: postgresql
    state: restarted
  tags: postgres_restart
