- name: allow LAN access to postgres
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    insertafter: '# IPv4 local connections:'
    line: "host all all 192.168.88.0/24 md5"

- name: open postgresql port
  replace:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: "#listen_addresses = 'localhost'"
    replace: "listen_addresses = 'localhost, {{ node1_ip }}'"

- name: create default postgres user password
  become: true
  become_method: sudo
  become_user: postgres
  postgresql_user:
    db: postgres
    name: postgres
    password: "{{ default_password }}"
    state: present

- name: allow CNI access to postgres
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    insertafter: '# IPv4 local connections:'
    line: "host keycloak keycloak 10.244.0.0/16 md5"
  when: keycloak_enabled

- name: restart postgres now
  service:
    name: postgresql
    state: restarted
