- name: Cert-manager. Addinga helm repo.
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    
- name: Cert-manager. Deploy cert-manager.
  community.kubernetes.helm:
    name: cert-manager
    namespace: cert-manager
    create_namespace: true
    chart_ref: jetstack/cert-manager
    update_repo_cache: 
    chart_version: v1.4.0
    values:
      installCRDs: true
