---
- hosts: all
  become: yes
  roles:
    - common
  tags: 
    - common 

- hosts: kubernetes_master
  tags: kubernetes_master
  become: yes
  roles:
    - docker
#    - prometheus
#    - elk
    - kubernetes_master

- hosts: kubernetes_nodes
  tags: kubernetes_nodes
  become: yes
  roles:
#    - node-exporter
#    - cadvisor
#    - elk
    - docker
    - kubernetes

- hosts: kubernetes_master
  become: yes
  roles:
    - { role: metallb, tags: metallb, when: metallb|default(true) }

- hosts: kubernetes_master
  become: yes
  roles:
    - { role: ingress-nginx, tags: ingress-nginx, when: ingress_nginx_enabled|default(true) }

- hosts: kubernetes_master
  tags: ceph
  become: yes
  roles:
    - { role: ceph, when: ceph_enabled|default(false) }

- hosts: postgres
  become: yes
  roles:
    - { role: postgres, tags: postgres, when: postgres_enabled|default(false) }

- hosts: kubernetes_master
  become: yes
  roles:
    - { role: keycloak, tags: keycloak, when: keycloak_enabled|default(false) }
