---
- hosts: kubernetes_master
  become: yes
  roles:
    - common
- hosts: kubernetes_master
#    - prometheus
#    - elk
  roles:
    - docker
    - kubernetes_master
  become_user: k8s
  tags:
  - kubernetes_master

- hosts: kubernetes_nodes
  roles:
    - common
#    - node-exporter
#    - cadvisor
#    - elk
    - docker
    - kubernetes
  tags: 
  - kubernetes_nodes
  become_user: k8s
