---
- hosts: all
  tags:
    - pure_kubernetes_install
  become: yes
  roles:
    - { role: common, tags: common }

- hosts: kubernetes_master
  tags: 
    - kubernetes_master
    - pure_kubernetes_install
  become: yes
  roles:
    - docker
    - kubernetes_master

- hosts: kubernetes_nodes
  tags: 
   - kubernetes_nodes
   - pure_kubernetes_install
  become: yes
  roles:
    - docker
    - kubernetes

- hosts: postgres_master
  become: yes
  roles:
    - { role: postgres, tags: postgres, when: postgres_enabled|default(false) }

- hosts: postgres_standby
  become: yes
  roles:
    - { role: postgres-standby, tags: postgres_standby, when: postgres_replication_enabled|default(false) }

- hosts: storage
  tags: storages
  become: yes
  roles:
    - { role: storage/ceph, tags: ceph, when: ceph_enabled|default(false) }
    - { role: storage/nfs, tags: nfs, when: nfs_enabled|default(true) }

- hosts: kubernetes_deployments
  tags: kubernetes_deployments
  become: yes
  roles:
    - { role: metallb, tags: metallb, when: metallb|default(true) }
    - { role: cert-manager, tags: cert-manager, when: cert_manager_enabled|default(false) }
    - { role: prometheus, tags: prometheus, when: prometheus_enabled|default(false) }
    - { role: ingress-nginx, tags: ingress-nginx, when: ingress_nginx_enabled|default(true) }
    - { role: keycloak, tags: keycloak, when: keycloak_enabled|default(false) }
    - { role: efk, tags: efk, when: efk_enabled|default(false) }
