---
- name: Pre-installation additional tools.
  hosts: all
  #  tags:
  #    - pure_kubernetes_install
  become: yes
  roles:
    - { role: common, tags: common }

- name: Set up kubernetes control plane nodes
  hosts: kube_control_plane
  tags: 
    - kube_control_plane
    - pure_kubernetes_install
  become: yes
  roles:
    - docker
    - kube_control_plane

- name: Set up kubernetes worker nodes
  hosts: kubernetes_nodes
  tags: 
   - kubernetes_nodes
   - pure_kubernetes_install
  become: yes
  roles:
    - docker
    - kubernetes
 
- name: Scaling kubernetes nodes
  hosts: new_kubernetes_nodes
  tags: 
   - new_kubernetes_nodes
  become: yes
  roles:
    - { role: common, when: add_new_node|default(true) }
    - { role: docker, when: add_new_node|default(true) }
    - { role: kubernetes, when: add_new_node|default(true) }

- name: Upgrade controle plane nodes
  hosts: kube_control_plane
  serial: 1
  order: sorted
  tags:
    - upgrade_main_control_plane
    - upgrade_kubernetes_cluster
  become: yes
  roles:
    - { role: kubernetes_control_plane_upgrade, when: upgrade_kuberentes_cluster|default(true) }

- name: Upgrade worker nodes
  hosts: kubernetes_nodes
  tags:
    - upgrade_kubernetes_nodes
    - upgrade_kubernetes_cluster
  become: yes
  max_fail_percentage: 20
  serial: 1
  order: reverse_sorted
  roles:
    - { role: kubernetes_nodes_upgrade, when: upgrade_kubernetes_nodes|default(true) }

- name: Set up network storages
  hosts: storage
  tags: storages
  become: yes
  roles:
    - { role: storage/ceph, tags: ceph, when: ceph_enabled|default(false) }
    - { role: storage/nfs, tags: nfs, when: nfs_enabled|default(true) }

- name: Deploy kubernetes additional components
  hosts: kubernetes_deployments
  tags: kubernetes_deployments
  become: yes
  roles:
    - { role: metallb, tags: metallb, when: metallb|default(true) }
    - { role: cert-manager, tags: cert-manager, when: cert_manager_enabled|default(true) }
    - { role: prometheus, tags: prometheus, when: prometheus_enabled|default(true) }
    - { role: ingress-nginx, tags: ingress-nginx, when: ingress_nginx_enabled|default(true) }
    - { role: keycloak, tags: keycloak, when: keycloak_enabled|default(true) }
    - { role: efk, tags: efk, when: efk_enabled|default(true) }
