---
- hosts: 10.8.8.11
  become: yes
  vars:
  - user: vagrant
  tasks:
    - name: get vagrant user info
      getent:
        database: passwd
        key: "{{ user }}"
        fail_key: False

    - debug:
        var: getent_passwd

    - set_fact:
        pwd_alias: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"
      when: '"home" in getent_passwd'

    - debug:
        msg: "{{ pwd_alias }}"
      when: 'getent_passwd is '

    - name: add password to local file
      local_action:
        module: lineinfile
        path: ./k8s_passwd
        regexp: '^(.+)\R'
        line: "{{ pwd_alias }}"
        state: present
        create: yes
      when: '"home" in getent_passwd'
