---
- hosts: 10.8.8.11
  become: yes
  vars:
  - user: k8s_test
  tasks:
    - name: get vagrant user info
      getent:
        database: passwd
        key: "{{ user }}"
      ignore_errors: true
      register: user_existing

    - debug:
        var: getent_passwd 

    - set_fact:
        pwd_alias: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"
      when: user_existing is failed

    - debug:
        msg: "{{ pwd_alias }}"
      when: user_existing is failed

    - name: add password to local file
      local_action:
        module: lineinfile
        path: ./k8s_passwd
        regexp: '^\A(.+)$'
        line: "{{ pwd_alias }}"
        state: present
        create: yes
      when: user_existing is failed

    - name: creating test user
      user:
        name: "{{ user }}"
        state: present
        password: "{{ pwd_alias | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
      register: k8s_user_info

- hosts: 10.8.8.11
  vars:
  - user: k8s_test
  tasks:
  - name: create file in k8s user directory
    lineinfile:
      path: ~/test_file
      line: "This is {{ user }} user"
      create: yes
  
  - name: display file
    shell: "cat ~/test_file && ls -la ~/test_file"
    args:
      executable: /bin/bash
    register: cat_test_file

  - debug:
      var: cat_test_file
  become: yes
  become_user: k8s_test
