- hosts: etcd
#  serial: 1
#  order: reverse_sorted
  gather_facts: true
  become: yes
  tasks:
    - name: test
      debug:
        msg: |
          {% for host in groups['etcd'] %}
          {{ hostvars[host]['ansible_eth1']['ipv4']['address'] }} {{ host }} {{ host }}
          {% endfor %}
