- hosts: etcd[0:2]
#  serial: 1
#  order: reverse_sorted
  gather_facts: true
  become: yes
  tasks:
  - name: Patroni. Configure patroni.
    debug:
      msg: "{{ keepalived_state }}"
    vars:
      keepalived_state: "{% if inventory_hostname == groups['etcd'][0] %}MASTER{% else %}BACKUP{% endif %}"
