---
- hosts: 10.8.8.11
  become: yes
  tasks:
  - name: first
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      sysctl_file: ./test.conf
      reload: yes
      with_items:
      - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
      - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }

