- hosts: kube_control_plane
#  serial: 1
#  order: reverse_sorted
  gather_facts: true
  become: yes
  tasks:
  - name: debug
    shell: "kubectl get namespaces | cut -d' ' -f1 | grep -v \"NAME\""
    register: existing_namespaces

- name: Alertmanager. Create custom alert rules.
  template:
    src: /home/vagrant/provisioning/ansible/roles/prometheus/templates/alertmanager/warn-crit-routes-slack-receivers.yaml.j2
    dest: "/tmp/prometheus/{{ item }}-warn-crit-routes-slack-receivers.yaml"
  loop: "{{ existing_namespaces.stdout_lines }}"
  vars:
    alertmanagerconfig_namespace: "{{ item }}"

