- hosts: kubernetes_master
  become: yes
  vars:
    key_list:
      - one
      - two
    values_list:
      - apple
      - orange
  tasks:
    debug:
      msg: "{{ dict(key_list | zip(values_list)) }}"
