---
- hosts: postgres
  become: yes
  gather_facts: true
  tasks:
  - name: Patroni. Configure patroni.
    template:
      src: /home/vagrant/tmp/patroni{{ item }}.yml.j2
      dest: /tmp/config.yml
      force: yes
    register: patroni_config
    when: inventory_hostname == groups['postgres'][item]
    with_items:
      - 0
      - 1
      - 2

  - name: debug
    debug:
      var: patroni_config
