---
- hosts: etcd
  become: yes
  gather_facts: true
  tasks:
    - name: test
      debug:
        msg: "{{ group_names | regex_search('etcd') }}"
      delegate_to: "{{ groups['postgres'][0] }}"
      run_once: true
