apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
#metadata:
#  labels:
#    release: prometheus
#  name: go-rules.rules
#  namespace: prometheus
metadata:                                                                       
  labels:                                                                       
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 17.2.1
    release: prometheus
  name: go-rules.rules
  namespace: prometheus
spec:
  groups:
    - name: go-app-rules
      rules:

      - alert: GoCounterUp
        expr: up{job="go-counter"} == 1
        labels:                                                                                                                                   
          severity: critical                                                                                                                      
          app_type: go-app
        annotations:
          summaty: TEST ALERT. Go-counter app is up.
          description: Go-counter is up.

      - expr: rate(go_app_response_latency_seconds_sum[1m]) / rate(go_app_response_latency_seconds_count[1m])
        record: job:go_app_response_latency_seconds:ratelm

        # Alert for above 2 seconds latency
      - alert: GoAppLatencyAbove2sec
        expr: 2 < job:go_app_response_latency_seconds:ratelm < 5
        for: 2m
        labels:
          severity: warning
          app_type: go-app
        annotations:
          summary: Go app latency is unusual
          description: Go app latency on {{ $labels.instance }} instance of job {{ $labels.job }} is {{ $value }} for more than 2 minutes.
          app_link: 'http:192.168.88.212:8000/'

        # Alert latency above 5 seconds
      - alert: GoAppLatencyAbove5sec
        expr: job:go_app_response_latency_seconds:ratelm >= 5
        for: 2m
        labels:
          severity: critical
          app_type: go-app
        annotations:
          summary: Go app latency is too high!
          description: Go app latency of instance {{ $labels.instance }} for a job {{ $labels.job }} is {{ $value }} for more than 2 minutes
          app_link: 'http:192.168.88.212:8000/'

      - alert: GoAppRequestsAbove1000
        expr: promhttp_metric_handler_requests_total{job="go-counter"} > 1000
        for: 1m
        labels:
          app_type: go-app
          severity: unk
        annotations:
          summary: TEST ALERT. Go app requests above 1000
          description: Go app requests of instance {{ $labels.instance }} for a job {{ $labels.job }} is {{ $value }} for more than 1 minute
          app_link: 'htpp:192.168.88.212:8000/'
