apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 17.2.1
    release: prometheus
  name: prometheus-kube-prometheus-custom.rules
  namespace: prometheus
spec:
  groups:
    - name: my-rules
      rules:
      - expr: |-
          avg without(cpu)(
          rate(node_cpu_seconds_total{mode="idle"}[5m]))
        record: job:node_cpu_seconds:avg_idle
