---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: go-applications
  namespace: default
  labels:
    alertmanagerConfigs: go-applications
spec:
  route:
    matchers:
      - name: app_type
        value: go-app
    receiver: goapp-team
    routes:
      - matchers:
        - name: severity
          value: critical
        receiver: goapp-team-manager
      - matchers:
        - name: severity
          value: warning
        receiver: goapp-team-lead
    repeatInterval: 12h
  receivers:
  - name: goapp-team
    emailConfigs:
    - to: goapp.team.main@gmail.com
  - name: goapp-team-manager
    pagerdutyConfigs:
    - serviceKey:
        key: pager-password
        name: pager-config
#      url: 'https://events.pagerduty.com/generic/2010-04-15/create_event.json'
  - name: goapp-team-lead
    emailConfigs:
    - to: goapp.team.lead@gmail.com
---
apiVersion: v1
kind: Secret
metadata:
  name: pager-config
  namespace: default
stringData:
  pager-password: '9cb28365bb5f4702c0df64ee4993a1c7'
