---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: operation-systems-alerts
  namespace: prometheus
  labels:
    alertmanagerConfig: operation-systems-alerts
spec:
  route:
    matchers:
    - name: app_type
      value: (linux|windows)
      regex: true
    receiver: os-admin
    routes:
      - matchers:
        - name: app_type
          value: linux
        - name: namespace
          value: prometheus
        #groupBy: [category]
        receiver: linux
        routes:
          - matchers:
            - name: severity
              value: critical
            receiver: linux-team-manager
          - matchers:
            - name: severity
              value: warning
            receiver: linux-team-lead
      - matchers:
        - name: app_type
          value: windows
        - name: namespace
          value: prometheus
        receiver: windows
        routes:
          - matchers:
            - name: severity
              value: critical
            receiver: windows-team-manager
          - matchers:
            - name: severity
              value: warning
            receiver: windows-team-lead
    repeatInterval: 12h
#  inhibitRules:
#  - sourceMatch:
#    - name: severity
#      value: critical
#    - name: namespace
#      value: prometheus
#  - targetMatch:
#    - name: severity
#      value: warning
#    - name: namespace
#      value: prometheus
#    equal: ['app_type','category']
  receivers:
  - name: os-admin
    emailConfigs:
    - to: 'ikabod.zaisman@gmail.com'
  - name: linux
    emailConfigs:
    - to: 'jeronimo8008@gmail.com'
  - name: windows
    emailConfigs:
    - to: 'jeronimo808@gmail.com'
  - name: linux-team-manager
    slackConfigs:
    - apiURL: 
        key: slack-webhook
        name: slack-config
      channel: '#prometheus'
      username: 'prometheus-alert'
      color: '#2eb886'
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification' 
      text: |-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
  - name: linux-team-lead
    emailConfigs:
    - to: 'linux.team.lead1@gmail.com'
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-config
  namespace: prometheus
stringData: 
  slack-webhook: 'https://hooks.slack.com/services/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'
