- name: Ingress-nginx. Add helm repo.
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"
  tags:
    - upgrade_cluster_components

- name: Ingress-nginx. Deploy ingress-nginx.
  community.kubernetes.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    namespace: ingress-nginx
    create_namespace: yes
    update_repo_cache: yes
    force: yes
    values:
      controller:
        kind: DaemonSet
        hostNetwork: true
        hostPort:
          enabled: true
        toleration:
        - key: "node-role.kubernetes.io/master"
          operator: "Exist"
          effect: "NoSchedule"
#        tcp:
#          configMapNamespace: "$(POD_NAMESPACE)/tcp-services"
#        udp:
#          configMapNamespace: "$(POD_NAMESPACE)/udp-services"
        metrics:
          enabled: true
          serviceMonitor:
            namespace: prometheus
            enabled: true
            additionalLabels:
              release: prometheus
      tcp:
        22: "gitlab/gitlab-gitlab-shell:22"
  tags:
    - ingress_nginx_deploy
    - upgrade_cluster_components
