---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-kubernetes-rules
  namespace: kube-system
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 17.2.1
    release: prometheus
spec:
  groups:
    - name: custom-kubernetes-rules
      rules:
      - expr: kube_pod_status_phase{phase="Failed"}
        record: job:kube_pod_status:failed
      
      - alert: PodIsFailed
        expr: job:kube_pod_status:failed == 1
        for: 5m
        labels:
          severity: critical
          app_type: kubernetes
          category: pod
        annotations:
          summary: Pod is Failed.
          description: Pod {{ $labels.pod }} in {{ $labels.namespace }} namespace has been failed.
