- name: Patroni. Check master.
  uri:
    url: http://{{ item }}:8008/master
    follow_redirects: none
    method: GET
  register: patroni_master_check
  failed_when: patroni_master_check.status == 404
  loop: "{{ groups['postgres'] }}"

- name: Postgresql. Create gitlab database user.
  postgresql_user:
    login_host: "{{ vrrp_ipaddress }}"
    login_user: postgres
    login_password: "{{ default_password }}"
    port: "{{ haproxy_postgres_master_port }}"
    name: "{{ gitlab_db_user }}"
    password: "{{ default_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  loop: "{{ patroni_master_check.results }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  run_once: yes
  when: item.status == 200

- name: Postgresql. Create gitlab database.
  postgresql_db:
    login_host: "{{ vrrp_ipaddress }}"
    login_user: postgres
    login_password: "{{ default_password }}"
    login_port: "{{ haproxy_postgres_master_port }}"
    db: "{{ gitlab_db }}"
    owner: "{{ gitlab_db_user }}"
  loop: "{{ patroni_master_check.results }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  run_once: yes
  when: item.status == 200

- name: Postgresql. Create postgresql extentions for gitlab.
  postgresql_ext:
    name: btree_gist
    db: "{{ gitlab_db }}"
    login_host: "{{ vrrp_ipaddress }}"
    login_user: postgres
    login_password: "{{ default_password }}"
    port: "{{ haproxy_postgres_master_port }}"
  loop: "{{ patroni_master_check.results }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  when: item.status == 200
  run_once: yes
  tags: gitlab_extensions

- name: Postgresql. Create postgresql extentions for gitlab.
  postgresql_ext:
    name: pg_trgm
    db: "{{ gitlab_db }}"
    login_host: "{{ vrrp_ipaddress }}"
    login_user: postgres
    login_password: "{{ default_password }}"
    port: "{{ haproxy_postgres_master_port }}"
  loop: "{{ patroni_master_check.results }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  when: item.status == 200
  run_once: yes
  tags: gitlab_extensions
