- name: Patroni. Check master.
  uri:
    url: http://{{ item }}:8008/master
    follow_redirects: none
    method: GET
  register: patroni_master_check
  failed_when: patroni_master_check.status == 404
  loop: "{{ groups['postgres'] }}"

- name: Postgresql. Create gitlab database user.
  postgresql_user:
    login_host: "{{ haproxy_ip }}"
    login_user: postgres
    login_password: "{{ default_password }}"
    name: "{{ gitlab_db_user }}"
    password: "{{ default_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  loop: "{{ patroni_master_check.results }}"
  when: item.status == 200


- name: Postgresql. Create gitlab database.
  postgresql_db:
    login_host: "{{ haproxy_ip }}"
    login_user: postgres
    login_password: "{{ default_password }}"
    name: "{{ gitlab_db }}"
    owner: "{{ gitlab_db_user }}"
  loop: "{{ patroni_master_check.results }}"
  when: item.status == 200


- name: Postgresql. Create postgresql extentions for gitlab.
  postgresql_ext:
    name: "{{ item }}"
    db: "{{ gitlab_db }}"
    login_host: "{{ groups['postgres_master'][0] }}"
    login_user: postgres
    login_password: "{{ default_password }}"
  with_items:
    - btree_gist
    - pg_trgm
  loop: "{{ patroni_master_check.results }}"
  when: item.status == 200
  tags: gitlab_extensions

