- include: 0-install.yml
- include: 1-keycloak.yml
  when: keycloak_enabled|default(false)
  tags: postgres_keycloak_db_create
- include: 2-gitlab.yml
  when: gitlab_enabled|default(true)
  tags: postgres_gitlab_db_create
