- name: HAProxy. Unsures tmp directory exists.
  file:
    path: /tmp/haproxy
    state: directory

- name: HAProxy. Copy docker files and configs.
  template:
    src: "{{ item }}"
    dest: /tmp/haproxy/{{ item | regex_replace('\.j2$', '') }}
    force: yes
  with_items:
    - haproxy.cfg.j2
    - Dockerfile.j2
    - docker-compose.yml
  tags: test1212

- name: HAPRoxy. Build docker haproxy image.
  command: docker build -t {{ haproxy_image }} /tmp/haproxy/.

- name: HAPROXY. Deploy haproxy with docker-compose.
  command: docker-compose -f /tmp/haproxy/docker-compose.yml up -d
