- name: HAProxy. Unsures tmp directory exists.
  file:
    path: "{{ haproxy_docker_compose_dir }}"
    state: directory

- name: HAProxy. Copy docker files and configs.
  template:
    src: "{{ item }}"
    dest: /srv/docker/haproxy/{{ item | regex_replace('\.j2$', '') }}
    force: yes
  with_items:
    - haproxy.cfg.j2
    - Dockerfile.j2
    - docker-compose.yml

- name: HAPRoxy. Build docker haproxy image.
  command: docker build -t {{ haproxy_image }} {{ haproxy_docker_compose_dir }}/.
  tags: haproxy_service

- name: HAProxy. Create haproxy docker-compose service.
  template:
    src: haproxy-docker.service.j2
    dest: /etc/systemd/system/haproxy-docker.service
    owner: root
    group: root
    mode: '0711'

- name: HAPRoxy. Start haproxy docker service.
  systemd:
    name: haproxy-docker
    daemon_reload: yes
    enabled: yes
    state: started
