- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}
    create: yes

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

  #- name: creating kubernetes user
  #user:
  #  name: k8s
  #  state: present
  #  password: "{{ password | password_hash('sha512') }}"
  #  shell: /bin/bash
  #  create_home: yes
  #  group: adm
  #  register: user_info

- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777

- name: Join the nodes to cluster
  command: sh /tmp/join-command.sh
