apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8s-node1
  containers:
    - name: curl
      image: pstauffer/curl
      command: [ "sleep", "600" ]
