apiVersion: v1
data:
  alertmanager.yaml: |-
    Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KICBzbXRwX2Zyb206ICdpa2Fib2QuemFpc21h
    bkB5YW5kZXgucnUnCiAgc210cF9zbWFydGhvc3Q6IHNtdHAueWFuZGV4LnJ1OjU4NwogIHNtdHBf
    YXV0aF91c2VybmFtZTogJ2lrYWJvZC56YWlzbWFuQHlhbmRleC5ydScKICBzbXRwX2F1dGhfaWRl
    bnRpdHk6ICdpa2Fib2QuemFpc21hbkB5YW5kZXgucnUnCiAgc210cF9hdXRoX3Bhc3N3b3JkOiAn
    cnN5a2NieHFkam5wbnp3cScKcmVjZWl2ZXJzOgotIG5hbWU6ICJudWxsIgpyb3V0ZToKICBncm91
    cF9ieToKICAtIGFsZXJ0bmFtZQogIGdyb3VwX2ludGVydmFsOiA1bQogIGdyb3VwX3dhaXQ6IDMw
    cwogIHJlY2VpdmVyOiAibnVsbCIKICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJvdXRlczoKICAt
    IG1hdGNoOgogICAgICBhbGVydG5hbWU6IFdhdGNoZG9nCiAgICByZWNlaXZlcjogIm51bGwiCmlu
    aGliaXRfcnVsZXM6Ci0gc291cmNlX21hdGNoOgogICAgbmFtZXNwYWNlOiBwcm9tZXRoZXVzCiAg
    ICBzZXZlcml0eTogY3JpdGljYWwKICB0YXJnZXRfbWF0Y2g6CiAgICBuYW1lc3BhY2U6IHByb21l
    dGhldXMKICAgIHNldmVyaXR5OiB3YXJuaW5nCiAgZXF1YWw6IFsnYXBwX3R5cGUnLCdjYXRlZ29y
    eSddCnRlbXBsYXRlczoKLSAvZXRjL2FsZXJ0bWFuYWdlci9jb25maWcvKi50bXBsCg==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 17.2.1
    chart: kube-prometheus-stack-17.2.1
    heritage: Helm
    release: prometheus
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: prometheus
type: Opaque
