apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-kube-etcd
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 17.2.1
    chart: kube-prometheus-stack-17.2.1
    jobLabel: kube-etcd
    release: prometheus
  name: prometheus-kube-prometheus-kube-etcd
  namespace: kube-system
spec:
  ports:
  - name: http-metrics
    port: 2381
    protocol: TCP
    targetPort: 2381
  selector:
    component: etcd
  sessionAffinity: None
  type: ClusterIP
