- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  register: GPG
  tags: docker_install

- debug:
    var: GPG
    verbosity: 2
  tags: docker_install
  
- name: set up docker {{ docker_release }} repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    state: present
    filename: docker
  register: release
  tags: docker_install

- debug:
    var: release
    verbosity: 2 
  tags: docker_install

- name: update cache
  apt:
    update_cache: yes
  tags: docker_install

- name: creating docker group
  group:
    name: "{{ item }}"
    state: present
  with_items:
  - admin
  - docker
  tags: docker_install
  
- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: "{{ item }}"
  with_items:
  - admin
  - docker
  tags: docker_install

- name: install docker
  apt: name={{ item }} state=latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  tags: docker_install
  ignore_errors: yes

- name: fix bug then docker service crash on first startup. 
  replace:
    path: /lib/systemd/system/docker.service
    regexp: '^ExacStart=.*'
    replace: 'ExecStart=/usr/bin/dockerd -H unix:// --containerd=/run/containerd/conta
    inerd.sock'
 
- name: change docker runtime
  shell: |
    cat > /etc/docker/daemon.json <<EOF
    {
      "exec-opts": ["native.cgroupdriver=systemd"],
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "storage-driver": "overlay2"
    }
    EOF
    mkdir -p /etc/systemd/system/docker.service.d
    systemctl daemon-reload
    systemctl restart docker
  args:
    executable: /bin/bash
