---
- hosts: kubernetes_master
  become: yes
  tasks:
  - name:
    shell:
      cmd: kubectl version --client --short | grep -o '[0-9.]\+' | sed 's/..$//'
    register: kubernetes_version

  - name: set fact kubernetes version 
    set_fact:
      k8s_version: "{{ kubernetes_version.stdout }}"

  - debug:
      var: kubernetes_version.stdout
