- name: create nginx configmap
  template:
    src: nginx-proxy-for-ceph.yml.j2
    dest: "{{ home_env }}/nginx-proxy-for-ceph.yml.j2"

- name: apply nginx configmap
  command: "kubectl apply -f {{ home_env }}/nginx-proxy-for-ceph.yml.j2"
