---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack.infrastructure
  namespace: prometheus
  labels:
    alertnamagerConfig: slack.infrastructure
spec:
  route:
    matchers:
      - name: app_type
        value: linux
    receiver: linux
  receivers:
  - name: linux
    slackConfigs:
    - apiURL:
        key: slack-password
        name: slack.infrastructure.secret
      channel: '#node-alerts'
      username: 'prometheus-alert'
      color: '#2eb886'
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification' 
      text: |-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: slack.infrastructure.secret
  namespace: prometheus
stringData:
  slack-password: 'https://hooks.slack.com/services/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'
