apiVersion: v1
data:
  alertmanager.yaml: |-
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 17.2.1
    chart: kube-prometheus-stack-17.2.1
    heritage: Helm
    release: prometheus
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: prometheus
type: Opaque
