- name: Prometheus. Add helm repo.
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Prometheus. Deploy prometheus.
  community.kubernetes.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    namespace: prometheus
    create_namespace: yes
    update_repo_cache: yes
    chart_version: 17.2.1
    wait: yes
    wait_timeout: 600s
    values:
      kubeEtcd:
        service:
          enabled: true
          port: 2381
          targetPort: 2381
      alertmanager:
        service:
          loadBalancerIP: "{{ alertmanager_lb_ip }}"
          type: LoadBalancer
      grafana:
        adminPassword: "{{ default_password }}"
        ingress: 
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
            #cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - grafana.alexmaron.xyz
          tls:
          - secretName: grafana-tls
            hosts:
            - grafana.alexmaron.xyz
      prometheus:
        resources:
          requests:
            memory: 400Mi
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: nfs-client
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 8Gi
        service:
          loadBalancerIP: "{{ prometheus_lb_ip }}"
          type: LoadBalancer
        additionalScrapeConfigs: []
      nodeExporter:
        resources:
          limits:
            cpu: 10m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 32Mi
      prometheusOperator:
        namespaces:
          releaseNamespace: true
          additional:
          - kube-system
          - default
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi

- name: Alertmanager. Create alertmanager config.
  template:
    src: pure-alertmanager-conf.yaml.j2
    dest: /tmp/pure-alertmanager-conf.yaml.j2
  tags: test444

- name: Alertmanager. Encode alertmanager config.
  command: base64 /tmp/pure-alertmanager-conf.yaml.j2
  register: alertmanagerconfig_base64
  tags: test444

- name: Alertmanager. Create prometheus-operator manifest which contains alertmanager config.
  lineinfile:
    path: /tmp/pure-alertmanager-conf.yaml.j2
    insertafter: '  alertmanager.yaml: |-'
    line: |4 
        "{{ alertmanagerconfig_base64 }}"
  tags: test444


