- name: Prometheus config. Change kubernetes scheduler listen address.
  replace:
    path: /etc/kubernetes/manifests/kube-scheduler.yaml
    regexp: '    - --bind-address=.*'
    replace: "    - --bind-address={{ groups['kube_control_plane'][0] }}"

- name: Prometheus config. Change kubernetes kube proxy listen address.
  shell:
    cmd: | 
        kubectl -n kube-system get cm kube-proxy -o yaml > /tmp/kube-proxy-cm.yml && \
        sed -i 's/.*metricsBindAddress.*/    metricsBindAddress: \"0.0.0.0:10249\"/' /tmp/kube-proxy-cm.yml && \
        kubectl apply -f /tmp/kube-proxy-cm.yml

- name: Prometheus config. Expose kubernetes etcd metrics for "{{ groups['kube_control_plane'][0] }}"
  replace:
    path: /etc/kubernetes/manifests/etcd.yaml
    regexp: '    - --listen-metrics-urls=.*'
    replace: "    - --listen-metrics-urls=http://127.0.0.1:2381,http://{{ groups['kube_control_plane'][0] }}:2381"
