---
# tasks file for roles/prometheus
- include: 0-install.yml
  tags: prometheus_install
- include: 1-config.yml
  tags: prometheus_config
- include: 2-blackbox_install.yml
  when: blackbox_enabled|default(false)
  tags: pushgateway_install
- include: 3-pushgateway.yml
  when: pushgateway_enabled|default(false)
  tags: pushgateway_install
