- name: Gitlab. Add helm repo.
  community.kubernetes.helm_repository:
    name: gitlab
    repo_url: https://charts.gitlab.io/

- name: Gitlab. Deploy gitlab with helm.
  community.kubernetes.helm:
    name: gitlab
    namespace: gitlab
    create_namespace: yes
    chart_ref: gitlab/gitlab
    version: 5.3.3
    values:
      global:
        edition: ce
      hosts:
      ingress:
        hostname: gitlab.alexmaron.xyz
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        tls: true
    certmanager:
      install: false
