- name: Gitlab. Add helm repo.
  community.kubernetes.helm_repository:
    name: gitlab
    repo_url: https://charts.gitlab.io/

- name: Gitlab. Create secret for password.
  template:
    src: gitlab-postgresql-password.yaml.j2
    dest: /tmp/gitlab-postgresql-password.yaml

- name: Gitlab. Create namespace.
  command: kubectl create namespace gitlab

- name: Gitlab. Create namespace.
  command: kubectl apply -f /tmp/gitlab-postgresql-password.yaml

- name: Gitlab. Deploy gitlab with helm.
  community.kubernetes.helm:
    name: gitlab
    namespace: gitlab
    create_namespace: yes
    chart_ref: gitlab/gitlab
    chart_version: 5.3.3
    values:
      prometheus:
        install: false
      nginx-ingress:
        enabled: false
      certmanager-issuer:
        email: ikabod.zaisman@gmail.com
      global:
        shell:
          internalPort: 2222
        edition: ce
        hosts: 
          domain: gitlab.alexmaron.xyz
          externalIP: "194.28.31.181"
        psql:
          host: "{{ vrrp_ipaddress }}"
          password:
            secret: gitlab-postgresql-password
            key: postgres-password
          port: "{{ haproxy_postgres_master_port }}"
        ingress:
          enabled: true
          configureCertmanager: false
          class: nginx
          hostname: gitlab.alexmaron.xyz
          annotations:
            kubernetes.io/tls-acme: true
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          tls:
            enabled: true
      gitlab:
        webservice:
          ingress:
            tls:
              secretName: gitlab-tls
      registry:
        ingress:
          tls:
            secretName: registry-tls
      minio:
        ingress:
          tls:
            secretName: minio-tls
      certmanager:
        install: false
      postgresql:
        install: false
  tags: gitlab_redeploy

- name: Gitlab. Create prometheus serviceMonitors.
  command: kubectl apply -f {{ item }}
  with_items:
    - gitlab-exporter-sm.yaml
    - gitlab-redis-sm.yaml
    - gitlab-service-monitor.yaml

