- name: install additional tools
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

#####################################
- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  register: GPG
- debug:
    var: GPG
    verbosity: 2
  
#####################################
- name: set up docker {{ docker_release }} repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    state: present
    filename: docker
    update_cache: yes
  register: release
- debug:
    var: release
    verbosity: 2 

#####################################
- name: install docker
  apt: name={{ item }} state=latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add vagrant user to docker group
  user:
    name: vagrant
    group: docker
