- name: install additional tools
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  tags: docker_install

#####################################
- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  register: GPG
  tags: docker_install

- debug:
    var: GPG
    verbosity: 2
  tags: docker_install
  
#####################################
- name: set up docker {{ docker_release }} repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    state: present
    filename: docker
  register: release
  tags: docker_install

- debug:
    var: release
    verbosity: 2 
  tags: docker_install

- name: update cache
  apt:
    update_cache: yes
  tags: docker_install

- name: creating docker group
  group:
    name: docker
    state: present
  tags: docker_install
  
- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
  tags: docker_install

#####################################
- name: install docker
  apt: name={{ item }} state=latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  tags: docker_install
 
- name: remove docker
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
  - docker-ce
  - docker-ce-cli
  - containerd-io
  tags: delete_docker
